<a href="https://colab.research.google.com/github/Narangaraw411/Dive-into-code/blob/main/Implementation_of_matrix_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Problem 1] Matrix product is calculated manually Solve the matrix product of A and B by hand.

Please also explain the calculation process using markdown text.

[Problem 2] Calculation by NumPy function This matrix product of NumPy can be easily calculated using np.matmul() or np.dot() , or the @ operator.

In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_ndarray = np.dot(a_ndarray, b_ndarray)
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_ndarray = np.matmul(a_ndarray, b_ndarray)
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_ndarray = a_ndarray@b_ndarray
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


[Problem 3] Implementation of calculation of a certain element When doing the calculations by hand, you may have first paid attention to row 0 of matrix A and column 0 of matrix B, and then performed the following calculations.

In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[1,2,3],[4,5,6],[7,8,9]]

total=0
for i in range(0,len(a)):
  total=total + a[0][i]*b[i][0]
print (total)


30


[Problem 4] Creating a function that performs matrix multiplication Extend the code in Problem 3 to complete the matrix product scratch implementation. It should be a function that takes matrices A and B as arguments and returns the matrix product.

In [1]:
def matrix(a,b):
  total=0
  total_1=0
  total_2=0
  for i in range(0,len(a)):
    total=total + a[0][i]*b[i][0]
    total_1=total_1 + a[1][i]*b[i][1]
    total_2=total_2 + a[2][i]*b[i][2]
  return total, total_1, total_2
print(list(matrix([[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]])))


[30, 81, 150]


[Problem 5] Judge the input whose calculation is not defined Depending on the implementation method, the function created in Problem 4 may work even if this D and E array is input. In this case, incorrect calculations will be made. Also, even if an error occurs in the middle, a message that is hard to understand why the error occurred is displayed directly.

In [2]:
def matrix(a,b):
  total=0
  total_1=0
  for i in range(0,len(a)):
    total=total + a[0][i]*b[i][0]
    total_1=total_1 + a[1][i]*b[i][1]
  return total, total_1,
  if a.shape[0]==b.shape[1]:
    return total, total_1, total_2
  else:
    print("Warning")
    return none
print(list(matrix([[-1, 2, 3], [4, -5, 6]],[[-9, 8, 7], [6, -5, 4]])))



[21, 57]


[Problem 6] Transposition Transposing one matrix allows you to calculate the matrix product.

In [6]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_ndarray = np.dot(a_ndarray, b_ndarray).T
print(c_ndarray)

[[  6  12 -18]
 [ 29  52 -51]
 [-20  38 -48]]
